# Generated by Django 4.1.12 on 2023-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskslist',
            name='task_type',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
