# Generated by Django 4.1.12 on 2023-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_taskslist_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskslist',
            name='task_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
