# Generated by Django 4.1.12 on 2023-12-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_alter_taskslist_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskslist',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
