# Generated by Django 4.1.12 on 2023-12-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0004_taskslist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='state',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
